In [1]:
import pandas as pd
import numpy as np

In [3]:
df= pd.read_csv("spam.csv")
df.head()

Category                                            Message
0      ham  Go until jurong point, crazy.. Available only ...
1      ham                      Ok lar... Joking wif u oni...
2     spam  Free entry in 2 a wkly comp to win FA Cup fina...
3      ham  U dun say so early hor... U c already then say...
4      ham  Nah I don't think he goes to usf, he lives aro...

In [5]:
df.Category.value_counts()

Category
ham     4825
spam     747
Name: count, dtype: int64

In [7]:
df['spam']=df['Category'].apply(lambda x: 1 if x=='spam' else 0)

In [8]:
df.head()

Category                                            Message  spam
0      ham  Go until jurong point, crazy.. Available only ...     0
1      ham                      Ok lar... Joking wif u oni...     0
2     spam  Free entry in 2 a wkly comp to win FA Cup fina...     1
3      ham  U dun say so early hor... U c already then say...     0
4      ham  Nah I don't think he goes to usf, he lives aro...     0

In [10]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(df.Message, df.spam,test_size=0.25)

In [12]:
x_train.shape

(4179,)

In [13]:
x_test.shape

(1393,)

In [18]:
from sklearn.feature_extraction.text import CountVectorizer
cv = CountVectorizer()
x_train_cv=cv.fit_transform(x_train.values)
x_train_cv.toarray()

array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       ...,
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]])

In [19]:
x_train_cv.shape

(4179, 7510)

In [22]:
dir(cv)

['__annotations__',
 '__class__',
 '__delattr__',
 '__dict__',
 '__dir__',
 '__doc__',
 '__eq__',
 '__format__',
 '__ge__',
 '__getattribute__',
 '__getstate__',
 '__gt__',
 '__hash__',
 '__init__',
 '__init_subclass__',
 '__le__',
 '__lt__',
 '__module__',
 '__ne__',
 '__new__',
 '__reduce__',
 '__reduce_ex__',
 '__repr__',
 '__setattr__',
 '__setstate__',
 '__sizeof__',
 '__str__',
 '__subclasshook__',
 '__weakref__',
 '_char_ngrams',
 '_char_wb_ngrams',
 '_check_feature_names',
 '_check_n_features',
 '_check_stop_words_consistency',
 '_check_vocabulary',
 '_count_vocab',
 '_get_param_names',
 '_get_tags',
 '_limit_features',
 '_more_tags',
 '_parameter_constraints',
 '_repr_html_',
 '_repr_html_inner',
 '_repr_mimebundle_',
 '_sort_features',
 '_stop_words_id',
 '_validate_data',
 '_validate_ngram_range',
 '_validate_params',
 '_validate_vocabulary',
 '_warn_for_unused_params',
 '_white_spaces',
 '_word_ngrams',
 'analyzer',
 'binary',
 'build_analyzer',
 'build_preprocessor',
 'bui

In [26]:
cv.vocabulary_

{'good': 3118,
 'morning': 4454,
 'plz': 5099,
 'call': 1560,
 'me': 4276,
 'sir': 5989,
 'ok': 4766,
 'the': 6604,
 'theory': 6620,
 'test': 6575,
 'when': 7247,
 'are': 1012,
 'going': 3106,
 'to': 6727,
 'book': 1388,
 'think': 6636,
 'it': 3670,
 'on': 4786,
 '21': 348,
 'may': 4270,
 'coz': 2006,
 'thought': 6657,
 'wanna': 7151,
 'go': 3093,
 'out': 4860,
 'with': 7313,
 'jiayin': 3732,
 'but': 1531,
 'she': 5887,
 'isnt': 3666,
 'free': 2925,
 'will': 7286,
 'stop': 6290,
 'itself': 3678,
 'however': 3446,
 'suggest': 6380,
 'stays': 6260,
 'someone': 6101,
 'that': 6601,
 'be': 1235,
 'able': 737,
 'give': 3076,
 'ors': 4843,
 'for': 2883,
 'every': 2618,
 'stool': 6289,
 'yes': 7457,
 'sura': 6417,
 'in': 3559,
 'sun': 6391,
 'tv': 6882,
 'lol': 4073,
 'guai': 3192,
 'shd': 5886,
 'haf': 3227,
 'seen': 5806,
 'him': 3360,
 'he': 3296,
 'naughty': 4573,
 'so': 6085,
 'today': 6732,
 'can': 1585,
 'jogging': 3742,
 'nokia': 4662,
 'or': 4823,
 'motorola': 4465,
 'upto': 6986,
 '

In [27]:
x_train_np=x_train_cv.toarray()
x_train_np

array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       ...,
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]])

In [29]:
from sklearn.naive_bayes import MultinomialNB

model = MultinomialNB()
model.fit(x_train_cv,y_train)


MultinomialNB()

In [30]:
x_test_cv=v.transform(x_test)

In [31]:
from sklearn.metrics import classification_report
y_pred=model.predict(x_test_cv)
print(classification_report(y_test, y_pred))

              precision    recall  f1-score   support

           0       0.99      1.00      0.99      1221
           1       0.98      0.91      0.94       172

    accuracy                           0.99      1393
   macro avg       0.98      0.95      0.97      1393
weighted avg       0.99      0.99      0.99      1393



In [37]:
email=[ '''Hello Ruchi,
Welcome to your Oracle jobs update. Check out our latest roles for you:

Data Engineer
Software Developer 4
Software Developer 3
Software Developer 2
Principal Software Developer''' ]
email_count = v.transform(email)
model.predict(email_count)

  

array([1])

BY USING PIPELINE

In [41]:
from sklearn.pipeline import Pipeline

model2=Pipeline([ ('vectorizer', CountVectorizer()),
                 ('nb',MultinomialNB())
                ])
           

In [43]:
model2.fit(x_train,y_train)

Pipeline(steps=[('vectorizer', CountVectorizer()), ('nb', MultinomialNB())])

In [44]:
y_pred=model2.predict(x_test)

print(classification_report(y_test,y_pred))

              precision    recall  f1-score   support

           0       0.99      1.00      0.99      1221
           1       0.98      0.91      0.94       172

    accuracy                           0.99      1393
   macro avg       0.98      0.95      0.97      1393
weighted avg       0.99      0.99      0.99      1393

